"""adding one to many

Revision ID: 7821b8a177a7
Revises: 6c6bf276baa3
Create Date: 2020-03-10 10:41:05.284999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7821b8a177a7'
down_revision = '6c6bf276baa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'buy')
    op.add_column('item', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'customer', ['buyer_id'], ['customer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'buyer_id')
    op.add_column('customer', sa.Column('buy', sa.VARCHAR(length=40), nullable=True))
    # ### end Alembic commands ###
